<?php

namespace AppBundle\Repository;

/**
 * HighscoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HighscoreRepository extends \Doctrine\ORM\EntityRepository
{
}
