<?php

namespace AppBundle\Repository;

/**
 * Koppel_tocht_locatieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Koppel_tocht_locatieRepository extends \Doctrine\ORM\EntityRepository
{
}
