<?php

namespace AppBundle\Repository;

/**
 * LocationUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationUserRepository extends \Doctrine\ORM\EntityRepository
{
}
