<?php

namespace AppBundle\Repository;

/**
 * markerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class markerRepository extends \Doctrine\ORM\EntityRepository
{
}
