<?php

namespace AppBundle\Repository;

/**
 * SpeurtochtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeurtochtRepository extends \Doctrine\ORM\EntityRepository
{
}
