<?php

namespace AppBundle\Repository;

/**
 * VraagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VraagRepository extends \Doctrine\ORM\EntityRepository
{
}
